[package]
name = "wgpu_backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytemuck = "1.13.1"
egui = "0.22.0"
wgpu = "0.16.1"
